### ISSUE TITLE
Indentation Consistency Issue

### ISSUE THREAD

**Issue by devquint** [20-1-SKKU-OSS/c9-python-getting-started#11]
In the overall project, it seems that some of the indentation have inconsistency.

Python 3 disallow the mixture of tab and space, and PEP 8 recommend to use only one, especially recommend to use 4 spaces per indentation. 
However there seems to be the bug with Github, making only one space head of each line.

Therefore I think we should make some indentation consistency(to 1 tab per indent) and make PR to original repository.
Maybe we'd rather make one branch for this issue, what about your opinion?

Following is the related PR: #10 #9 #6

**Comment by Hyuntae-Jeong** [comment]
I agree. This might occur some users to get confused.

**Comment by Dorika0203** [comment]
I agree.
And about bugs, when I've tried tab key while fixing codes on github page, it didn't work - tab key acted same as space bar key.... but today, tab key and space bar key work well distinguished... I think bug I said may be not on github, but by browser or something... sorry for confusing you.

indention 통일을 위한 브랜치 생성에는 동의합니다.
그리고 그 버그 관련 해서 인데, 어제 제가 생겼던 문제가 깃헙 페이지에서 코드를 바로 수정할 때, 탭 키를 눌러도 스페이스 바 키처럼 한 칸만 띄어지는 현상 이였습니다. 그래서 indent를 통일하기 위해 local로 다운로드를 해서 작업을 했구요. 근데 오늘 다시 해보니까 tab키가 정상 작동합니다.. 어제는 왜 그랬는지 모르겠지만 깃허브 버그가 아니라 브라우저 문제던가 한영 키 문제던가 그런 문제였을 것 같습니다.. 결론은 버그 같은거 없어요! 혼란을 드려서 죄송합니다.

**Comment by devquint** [comment]
Alright, I checked we can use 4 spaces indentation [with @ChaeyeonSeo 's commit](https://github.com/20-1-SKKU-OSS/c9-python-getting-started/blob/87fcdccb86f312388d1dc320198fcacf9b7f7236/more-python-for-beginners/03%20-%20Classes/properties_class.py). 

Maybe there's no objection, making the new branch to deal with this issue is foregone conclusion. I think we should discuss about what to choose between `4 spaces indentation` and `1 tab indentation`.
It seems most of this projects uses `1 tab indentation`, but PEP 8 recommend `4 spaces indentation`.

What do you think of this? @Dorika0203 @ChaeyeonSeo @Hyuntae-Jeong @jesusleejy 
In my opinion, we should use `4 spaces indentation` because first lecture of this project deals with PEP 8, and PEP 8 recommends it.

**Comment by ChaeyeonSeo** [comment]
I think it's a good idea.

**Comment by devquint** [comment]
@ChaeyeonSeo You mean using `4 spaces indentation`? or just about this overall issue?
And I wish other teammates to give your own opinion ASAP.

**Comment by ChaeyeonSeo** [comment]
I mean using 4 spaces indentation.

**Comment by Hyuntae-Jeong** [comment]
I think using 4 spaces indentation is better choice, since of the reasons of this project's first lecture dealing with PEP 8 which recommends 4 spaces. Also due to the problems user Dorika0203 has experience.

**Comment by Dorika0203** [comment]
I agree with 4 space indentation and making a new branch for this. Actually, I've unified indentation on #10  to tab - but I think 4 spaces would be better for compatibility.

**Comment by devquint** [comment]
Alright, I think we had enough time to discuss. Let's conclude that we proceed project to integrate all indentation to `4 spaces`.
Then I gonna close this issue, and somebody else make another issue about this - for detailed works.
Let's discuss detailed to-do there.
