### ISSUE TITLE
4 Spaces Indentation issue

### ISSUE THREAD

**Issue by ChaeyeonSeo** [20-1-SKKU-OSS/c9-python-getting-started#15]
We decided to use 4 spaces indentation in the project in the last issue #11 .

Let's discuss how to divide our roles, and how to use branches.
I think dividing categories and have your own branch, then merge it to one branch at last would be a good choice. Please give your opinion, and let's discuss and choose the best way to do.

**Comment by devquint** [comment]
Separating branch would be good to follow our convention.
- master
   - indent-4space
        - indent-pfb
        - indent-mpfb
        - indent-empfb

and then take part in separate by specific chapter, like
- master
   - indent-4space
        - indent-pfb
            - chapter1t10
            - chapter11t20
        - indent-mpfb
            - ...
        - indent-empfb

However it's quite dirty, so what about making individual issue and naming branch with its own issue number, like
`Issue #16: Indentation Integration - python for beginner, chapter 1 ~ 10`
`Issue #17: Indentation Integration - python for beginner, chapter 11 ~ 21`
and branch like
- master
   - indent-4space
        - indent-pfb
            - 16
            - 17
        - indent-mpfb
            - ...
        - indent-empfb

Then we do commit by every file, and PR by every branch-issue.
I think this would be enough for separating branch, and some rule for commit and PR.

**Comment by Dorika0203** [comment]
I am thinking of making a branch for total indent check&fix, and make 3 sub branches for python-for-beginners, more-python-for-beginners, even-more-python-for-beginners. Then maybe 3 people can check and commit indents corresponding codes to each branches.

**Comment by Dorika0203** [comment]
Oh, I think above Idea is better. I agree with that one.

**Comment by devquint** [comment]
As for the division of roles, it's a bit annoying but not difficult, so I think it would be better to divide them equally as much as possible. 
But I think we need to consider separating totally equal because each of us has could have their own circumstance - investing time would be varying. 
What about dividing each(pfb, mpfb, empfb) into four based on chapter, there will be a **total of 12**. I think it'd be good to each of us take **one to three branches** depending on individual ability/time.

**Comment by Hyuntae-Jeong** [comment]
I agree with dividing equally since it's not that hard job.
Also agree with making branches with simple names

**Comment by Dorika0203** [comment]
Okay. Then shall I start making issues starting from 16?

**Comment by devquint** [comment]
@Dorika0203 Let's talk about this more, not everyone of teammates participated in this issue.
Moreover we didn't conclude about this issue yet.

**Comment by Dorika0203** [comment]
@devquint OK.

**Comment by Hyuntae-Jeong** [comment]
@devquint can you tell me more about "dividing each(pfb, mpfb, empfb) into four based on chapter, there will be a total of 12."

**Comment by devquint** [comment]
@Hyuntae-Jeong 
For example let pfb(python-for-beginner), mpfb, empfb consists of 12, 20, 16 chapters respectively.

Divide pfb1-3, pfb4-6, pfb7-9, pfb10-12, mpfb1-5, ..., mpfb 16-20, empfb 1-4, ... empfb 13-16, total 12.
Then A want to participate in choose one, ex)pfb1-3. 
Maybe B(not A) get into job, ex)pfb4-6.
If A finish pfb1-3, he/she choose another one ex)mpfb1-5.

Anyone who want to start new job choose one and make issue and go on work.
If he/she finish it, start another job not chosen yet.
However limiting max job to 3, to give other for participation.
Then (maybe) everyone take part in this issue, according to their time.

-----

각 python-for-beginner, more-..., even-more...을 4개로 나누면 12개의 branch가 생길 겁니다. 여기에서 개인별로 시작할 때 하나를 골라서 작업을 하고, 그 작업을 마치면 다른 남은 것을 골라서 시작하는 방식으로 개인별로 1-3개의 branch를 담당해서 처리하자는 의미였습니다.

**Comment by ChaeyeonSeo** [comment]
I think it's a good idea, and I think start it from pfb to empfb is good way to finish each parts first.

**Comment by Hyuntae-Jeong** [comment]
@devquint That's Good Idea! 
좋은 아이디어 감사드립니다!

**Comment by jesusleejy** [comment]
@devquint Thank you for the good idea. I think each person should take two or three parts. It's not going to be difficult because it's a simple spacing operation. Because the contents of pfb are the most common, the two people who are in charge of pfb's work can handle two branches each, and the rest can handle about three branches.

**Comment by devquint** [comment]
I'll close this issue, and create another one about how to proceed and how to divide roles.
