### ISSUE TITLE
Unifying indentation to 4 spaces indent

### ISSUE THREAD

**Issue by devquint** [20-1-SKKU-OSS/c9-python-getting-started#20]
From the previous issues #15 #11 , we discussed about how to deal with indentation inconsistency issue.

We've discussed detailed how-to on #15, I gonna conclude about this issue.

This may be a simple issue, so we all can get to them easily. Therefore I want to divide them as equal as possible. 
However I found empfb uses `jupyter-notebook`, and indented quite well.
Let's divide total works into 12 parts,

- pfb (python-for-beginners) : Chapter 2 - 18
    - [x] pfb 2-4 @jesusleejy
    - [x] pfb 5-7 @ChaeyeonSeo 
    - [x] pfb 8-10 @jesusleejy
    - [x] pfb 11-13 @ChaeyeonSeo 
    - [x] pfb 14-16 @Hyuntae-Jeong 
    - [x] pfb 17-18 @Hyuntae-Jeong 

- mpfb (more-python-for-beginners) : Chapter 1 - 9
    - [x] mpfb 1-3 @Dorika0203 
    - [x] mpfb 4-6 @Dorika0203 
    - [x] mpfb 7-9 @Dorika0203 

- empfb (even-more-python-for-beginners-...) : Chapter 1 - 15
    - [x] empfb 1-5 @devquint 
    - [x] empfb 6-10 @jesusleejy
    - [x] empfb 11-15 @devquint 

If you want to start one job, pick one and mark like below

original: 
```markdown
- pfb
    - [ ] pfb 20-30
```

after picking:
```markdown
- pfb
    - [ ] pfb 20-30 @devquint 
```

after done (made PR):
```markdown
- pfb
    - [x] pfb 20-30 @devquint 
```

-----

Rules for indentation:

For some `def`, `for`, `while` and so on making code block, use `4 spaces indent`, not `tab`
like:
```python
for a in dict:
    if a in another_dict:
        do_something()
    do_other()
```

For making some long array and so on, let the no argument on first line, and do `4 spaces` and make newline for each or reasonable amount of arguments (Actually we can choose other way, but we'd rather unity it to one below, [detailed about this](https://www.python.org/dev/peps/pep-0008/#indentation))
like:
```python
foo = long_function_name(
    var_one, var_two,
    var_three, var_four
)
```
```python
foo = long_function_name(
    var_one, 
    var_two,
    var_three, 
    var_four
)
```
```python
# add one more level to function parameter to make it distinguishable from function body
def long_function_name(
        var_one, var_two, var_three, 
        var_four):
    print(var_one)
```
```python
airports = pd.Series(
    [
        'Seattle-Tacoma', 
        'Dulles', 
        'London Heathrow', 
        'Schiphol', 
        'Changi', 
        'Pearson', 
        'Narita'
    ]
)
```

-----

If you start your works, mark in this issue, and make another issue with name like
`Unifying indentation: more-python-for-beginners chapter 1-3`
and make branch with its issue name under suit branch like
- master
   - indent-unify
        - indent-pfb
            - issue-16 (issue-`<issue number>`)
            - issue-17
        - indent-mpfb
            - ...
        - indent-empfb

After done, make PR like `indent-pfb` <- `issue-17` and let others to double check it indented well.

-----

NOTE:
- do not choose more than 4 tasks
- do not get task 2 or more at the same time
- you may install jupyter notebook to fix empfb
- workflow: mark above of this post -> make an issue -> make a branch -> commits -> make PR -> mark above of this post

Anything more should be discussed about this, please comment in this issue.

**Comment by devquint** [comment]
@Hyuntae-Jeong I said that do not get 2 or more task same time. You didn't even made an issue one of them, so I removed both tagged. Tag **one** of them again and make issue before you start.

**Comment by Hyuntae-Jeong** [comment]
@devquint Okay Got it

**Comment by devquint** [comment]
All pull requests are made, please review as soon as possible.
