### ISSUE TITLE
Korean Translating

### ISSUE THREAD

**Issue by Dorika0203** [20-1-SKKU-OSS/c9-python-getting-started#27]
We've talked about making documents of Korean, for Korean beginners like us.

I think that making translated documents inside each chapter folder is not good idea, as there are many other beginners view this project who are not Korean.

Therefore, I suggest that making a new folder for Korean.. Let me know your thought.

저희가 한국어 번역본을 만들자고 했던 것에 대해서입니다.
한국어로 번역된 문서를 각 단원에 추가하는 것은 안 좋은 생각일 것 같습니다. 한국인이 아니신 파이썬 초보자 분들이 이 프로젝트를 보면 보기 좀 불편할 것 같아서요!

만약 번역을 진행한다면, Korean이라는 새로운  폴더를 하나 만들어서 거기에 단원별로 번역된 문서를 추가하는게 괜찮다고 생각하고 있습니다. 의견 부탁드립니다!

**Comment by devquint** [comment]
Our first draft about translating into Korean was doing after some improvements are done.

However due to our circumstance(just in front of deadline), wouldn't be better to give up translation task?
I thought about just translating a little bit of page, but I don't think it would be good both for Korean reader and project holder. This might only confusing user, because we might couldn't done translating whole partial thing(one of pfb, mpfb, empfb).

Therefore I think we'd rather give up translating and focus on improvement.

**Comment by Dorika0203** [comment]
Thank you for your opinion.
Actually, I've thought the same thing. This is open source project worldwide by microsoft, and adding Korean translation might be not look so good.

**Comment by Dorika0203** [comment]
> Our first draft about translating into Korean was doing after some improvements are done.
> 
> However due to our circumstance(just in front of deadline), wouldn't be better to give up translation task?
> I thought about just translating a little bit of page, but I don't think it would be good both for Korean reader and project holder. This might only confusing user, because we might couldn't done translating whole partial thing(one of pfb, mpfb, empfb).
> 
> Therefore I think we'd rather give up translating and focus on improvement.

Thank you for your opinion.  
Actually, I've thought the same thing. This is open source project worldwide by microsoft, and adding Korean translation might be not look so good.
Also, due date is comming.... I was thinking of not sleeping actually....

I totally agree with giving up translating.

의견 감사드립니다.
사실 저도 포기하는게 낫다고 생각했습니다.
말씀하신 대로, 이 프로젝트는 마이크로소프트에서 진행하기 시작한 전세계적인 OSS이고, 한국어 번역본을 추가하는 것이 보기 좋지는 않을 것 같다고 생각했습니다.
기한도 문제이고... 저는 밤샐 각오하고 있었습니다..

저도 그냥 번역은 진행하지 않고, 코드 검사랑 최근에 이야기 된 이슈(indent 등)에 대해서 집중하는 것이 나을 것 같습니다.

**Comment by Hyuntae-Jeong** [comment]
I also agree with your opinions. Translating into only Korean will make other country users uncomfortable. Also we cannot translate all of the files. Even though we do that, we cannot translate it in other languages. So I also think translating work can't be done.

위에 분들의 의견과 같은 의견을 갖고 있습니다. 한국어로만 번역하는게 다른 유저들 입장에서는 불편하게 느껴질 수도 있고 한국어 외에 다른 언어로 번역하는 것도 무리이기 때문에 저도 현재까지 진행된 작업에 집중하는 것이 낫다고 생각합니다.

**Comment by devquint** [comment]
Close: Just time to finalize project, no time to translate.
